GRANJA/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login
from cerdo import views
from django.conf.urls import handler404
from cerdo.views import handler404
 
handler404 = handler404

admin.autodiscover()
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^cerdo/', include('cerdo.urls')),
    url(r'^vista/', include('cerdo.urls', namespace='cerdos1', app_name='cerdoos1')),
    url(r'^login$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout_then_login, name='logout'),
]

if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cerdo/urls.py
from django.conf.urls import url, include
from cerdo import  views
from django.contrib.auth.views import login, logout_then_login
from django.contrib import admin


urlpatterns = [
	url(r'^ver', views.VistaCerdos, name='list_cerdos'),
    url(r'^crearCerdo/', views.CerdoCrear.as_view(), name='crear_cerdos'),
    url(r'^editarcerdo/(?P<pk>\d+)', views.CerdoEditar.as_view(), name='editar_cerdos'),
    url(r'^eliminarcerdo/(?P<pk>\d+)', views.CerdoEliminar.as_view(), name='eliminar_cerdos'),
    url(r'^buscar/', views.BuscarCerdo.as_view(), name='buscar_cerdo'),
    url(r'^pdfcerdo/', views.CrearPdfCerdo.as_view(), name="pdfcerdo"),
    url(r'^pdfcerdo1/', views.CrearPdfCerdo4.as_view(), name="pdfcerdo1"),
    url(r'^generoM/', views.FiltarGeneroM.as_view(), name="generoM"),
     url(r'^generoH/', views.FiltarGeneroH.as_view(), name="generoH"),

    #url(r'^BuscarCerdo1/(?P<nombre>\d+)/$', views.BuscarCerdo, name="buscar_cerdo-list"),
    #vacunas
    url(r'^vacunas/', views.VistaVacunas, name='list_vacunas'),
    
    url(r'^crearvacunas/', views.VacunaCrear.as_view(), name='crear_vacunas'),

    url(r'^editarvacunas/(?P<pk>\d+)', views.VacunaEditar.as_view(), name='editar_vacunas'),
    url(r'^eliminarvacunas/(?P<pk>\d+)', views.VacunaEliminar.as_view(), name='eliminar_vacunas'),
    url(r'^pdfVacuna/', views.CrearPdfVacunas.as_view(), name="pdfvacuna"),
    url(r'^buscarvacuna/', views.BuscarVacuna.as_view(), name='buscar_vacuna'),
    #partos
    url(r'^partos/', views.VistaPartos, name='list_partos'),
	url(r'^crearpartos/', views.PartosCrea.as_view(), name='crear_partos'),
    url(r'^editarpartos/(?P<pk>\d+)', views.PartoEditar.as_view(), name='editar_partos'),
    url(r'^eliminarpartos/(?P<pk>\d+)', views.PartoEliminar.as_view(), name='eliminar_partos'),
    url(r'^buscarparto/', views.BuscarParto.as_view(), name='buscar_parto'),
    url(r'^pdfparto/', views.CrearPdfParto.as_view(), name="pdfparto"),
   # url(r'^buscar/', views.BuscarCerdo.as_view(), name='buscar_cerdo'),   
]

cerdo/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

GENERO_CHOICES = (
    ('M', 'Macho'),
    ('H', 'Hembra'),
)

class Cerdos(models.Model):
	nombre = models.CharField('Nombre', max_length=50)
	genero = models.CharField(
        'Genero Animal', max_length=1,
        choices=GENERO_CHOICES, default='M')
	peso = models.CharField('Peso', max_length=50)
	status = models.BooleanField(default=True)

	def __str__(self):
		return '{}'.format(self.nombre)	

	class Meta:
		verbose_name = "Cerdos"
		verbose_name_plural = "Cerdos"


class Vacunas(models.Model):
	nombre = models.CharField('Nombre', max_length=50)
	cerdo = models.ForeignKey(Cerdos, null = True)
	descripcion = models.TextField('Descripcion')
	status = models.BooleanField(default=True)
	def __str__(self):
		return '{}'.format(self.nombre)
	class Meta:
		verbose_name = "Vacuna"
		verbose_name_plural = "Vacunas"

class Partos(models.Model):
	cerdo = models.ForeignKey(Cerdos, null = True)
	fecha_gestacion = models.DateField('Fecha de Gestacion')
	fecha_parto = models.DateField('Fecha de parto')
	numero_partos = models.IntegerField('Numero de partos')
	cantidad_por_parto = models.IntegerField('Cantidad de animales por parto')
	status = models.BooleanField(default=True)
	def __str__(self):
		return '{}'.format(self.cerdo)
	class Meta:
		verbose_name = "parto"
		verbose_name_plural = "partos"

def full_cerdo(self):
	return u'{} {} {}'.format(self.nombre, self.genero, self.peso)

def full_partos(self):
	return u'{} {} {} {} {}'.format(self.cerdo, self.fecha_gestacion, self.fecha_parto, self.numero_partos, self.cantidad_por_parto)

def full_vacunas(self):
	return u'{} {} {}'.format(self.nombre, self.cerdo, self.descripcion)

GRANJA/templates/parto/agregar_parto.html
{% extends "admin.html" %}
{% load staticfiles %}

{% block header %}<br><br>
    <br>
    <div class="container">
    <form method="post" class="form-center">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{hidden}}

        {% endfor %}<br><br><br><br>

        <div class="form-group ">
            <label class="container" for="{{form.cerdo.id_for_label}}"
                    class="col-sm-8 control-label">{{ form.cerdo.label }}</label>
                <div class="col-sm-8">
                    {{form.cerdo}}
                </div>
        </div>
        <div class="form-group">
                <label for="{{form.fecha_gestacion.id_for_label}}"
                        class="col-sm-8 control-label">{{ form.fecha_gestacion.label }}</label>
                    <div class="col-sm-8">
                        {{form.fecha_gestacion}}
         </div>
        </div>
        <div class="form-group">
                <label for="{{form.fecha_parto.id_for_label}}"
                        class="col-sm-8 control-label">{{ form.fecha_parto.label }}</label>
                    <div class="col-sm-8">
                    {{ form.fecha_parto }}

                    </div>
        </div>
        <div class="form-group">
                <label for="{{form.numero_partos.id_for_label}}"
                        class="col-sm-8 control-label">{{ form.numero_partos.label }}</label>
                    <div class="col-sm-8">
                        {{form.numero_partos}}
                      
                    </div>
        </div>
        <div class="form-group">
                <label for="{{form.cantidad_por_parto.id_for_label}}"
                        class="col-sm-8 control-label">{{ form.cantidad_por_parto.label }}</label>
                    <div class="col-sm-8">
                        {{form.cantidad_por_parto}}
                    </div>
        </div>
        <div class="form-group">
                <label for="{{form.status.id_for_label}}"
                        class="col-sm-8 control-label">{{ form.status.label }}</label>
                                           {{form.status}}
                   
        </div>

        <div class="form-group">
            
                <div class=" col-sm-offset-8 col-sm-8">
                        <a class="btn btn-primary pull-left" href="{% url 'list_partos' %}">Volver     </a>
                <input class="btn btn-primary pull-right" type="submit" name="submit"
                value="Guardar">
            </div>
        </div>


    </form>


</div><br><br><br><br><br><br><br><br
{% block  footer%}
		{% endblock %}
{% endblock %}

GRANJA/templates/parto/buscar.html
{% extends "admin.html" %} 


{% load staticfiles i18n %}

{% block header %}<br><br><br><br><br><br><br><br>

<h1 class="container">Listado de partos</h1>
	<div class="container">
			<table class="container">
					
				<thead>
                    <th><a class="btn btn-primary" href="{% url 'list_partos' %}"> Volver</a></th>
                  
					
				
					<th></th>
				
				</thead>
			</table>
		</div>

	</div>
	
	
	<div class="container">
		<table class="table">
			<thead>
			<th>
				Nombre
			</th>
			<th>
				Genero
			</th>
			<th>
				Peso
			</th>
			<th>
				{% if perms.cerdos.change_cerdos %}
				Editar
				{% endif %}
			</th>
			<th>
					{% if perms.cerdos.change_cerdos %}
				Eliminar
				{% endif %}
			</th>
		</thead>
		<tbody  >
				{% block content %}
				{%if parto %}
				{% for cer in parto %}
				<tr>
				<td>
					{{cer.cerdo}}
				</td>
				<td>
					{{cer.fecha_gestacion}}
				</td>
				<td>
					{{cer.fecha_parto}}
				</td>
				<td>
					{{cer.numero_partos}}
				</td>
				<td>
					{{cer.cantidad_por_parto}}
				</td>
				<td>
	
						{% if  perms.vacunas.change_vacunas %}
	
						<a class="btn btn-info" href="{% url 'editar_partos' cer.id %}">Editar</a>
						{% endif %}
	
	
				</td>
				<td>{% if  perms.vacunas.change_vacunas %}
						<a class="btn btn-danger" href="{% url 'eliminar_partos' cer.id %}">Eliminar</a>{% endif %}
				</td>
			</tr>
				{% endfor %}

				{%else%}
				<p align="center"  class="text-success fa-2x text-danger">No existen datos</p>

				{%endif%}

            {%endblock%}
			
		</tbody>
		
		</table>

	</table><br><br><br><br><br><br><br><br
	{% block  footer%}
	{% endblock %}

	

	</div>
{% endblock %}

GRANJA/templates/parto/eliminar_parto.html
{% extends "admin.html" %} 
{% load staticfiles %}

{% block header %}<br><br><br><br><br><br><br><br>
<br>
    <div class="container">
    <form method="post" class="form-center">
        {% csrf_token %}
        <p align="center"  class="text-success fa-2x text-danger">Seguro que desea eliminar el registro{{cerdoEliminar.full_cerdo}}</p>

        <div class="form-group">
                
                <div class=" container col-sm-offset-8 col-sm-8">
                    <a class="btn btn-primary pull-left" href="{% url 'list_cerdos' %}">Volver     </a>
                    <input class="btn btn-primary pull-right" type="submit" name="submit"
                    value="Eliminar">
                </div>
            </div>

    </form>
    
		</table><br><br><br><br><br><br><br><br
		{% block  footer%}
		{% endblock %}
{% endblock %}

GRANJA/templates/parto/list_partos.html
{% extends "admin.html" %}
{% load staticfiles i18n %}
{% block header %}<br><br><br><br><br><br><br><br>
<h1 class="container">Listado de Partos</h1>
	<div class="container">
			<table class="container">
				<thead>
					<th><a class="btn btn-primary" href="{% url 'crear_partos' %}"> Nuevo Parto</a></th>

					<th>
							<form class="container" method="POST" action="{% url 'buscar_parto'%}">
									{% csrf_token %}
								
								   <input class="search-query" placeholder="Buscar por nombre" type="Date" name="buscalo">
								
								   <input class=" btn btn-primary icon-search" type="submit" value="buscar">
								
							   </form>
							</div>
							<th><a class="btn btn-primary" href="{% url 'pdfparto' %}"> pdf</a></th>
					</th>

				</thead>
			</table>
		</div>

	</div>


	<div class="container">
		<table class="table">
			<thead>
			<th>
				Cerdo
			</th>
			<th>
				Fecha de Gestacion
			</th>
			<th>
				Fecha de Parto (Aprox.)
			</th>
			<th>
				Numero de partos
			</th>
			<th>
				Cantidad de Cerdos paridos
			</th>
			<th>
				{% if perms.vacunas.change_vacunas %}
				Editar
				{% endif %}
			</th>
			<th>
					{% if perms.vacunas.change_vacunas  %}
				Eliminar
				{% endif %}
			</th>
		</thead>
		<tbody  >
			
			{% for cer in parto1 %}
			<tr>
			<td>
				{{cer.cerdo}}
			</td>
			<td>
				{{cer.fecha_gestacion}}
			</td>
			<td>
				{{cer.fecha_parto}}
			</td>
			<td>
				{{cer.numero_partos}}
			</td>
			<td>
				{{cer.cantidad_por_parto}}
			</td>
			<td>

					{% if  perms.vacunas.change_vacunas %}

					<a class="btn btn-info" href="{% url 'editar_partos' cer.id %}">Editar</a>
					{% endif %}


			</td>
			<td>{% if  perms.vacunas.change_vacunas %}
					<a class="btn btn-danger" href="{% url 'eliminar_partos' cer.id %}">Eliminar</a>{% endif %}
			</td>
		</tr>
			{% endfor %}

		</tbody>

		</table><br><br><br><br><br><br><br><br
		{% block  footer%}
		{% endblock %}


	</div>
{% endblock %}

GRANJA/templates/parto/pdf.html
<!DOCTYPE html>
{% extends "admin3.html" %} 
{% load staticfiles i18n %}	
<html>
<head>
	<title></title>
	
</head>
<body>
		{% block  footer%}
		<center><p>Listado de cerdos</p><br>
	
		<table FRAME="border" RULES="none" >
				
			<thead>
				<tr >
	<th >nombre</th>
	<th >genero</th>
	<th >peso</th>
	</tr>
	</thead>
	<tbody ALIGN="center">
	
	{% for i in object_list1 %}
	<tr >
		<td  >{{i.cerdo}}</td>		
		<td  >{{i.fecha_gestacion}}</td>
		<td  >{{i.fecha_parto}}</td>
		<td  >{{i.numero_partos}}</td>
		<td  >{{i.cantidad_por_parto}}</td>
		
				
	</tr>
	{% endfor %}
	</tbody>
	</table>
	
	{% endblock %}
	

GRANJA/templates/parto/pruba.html
<form method="POST" action="">{% csrf_token %}
{{empaque.as_p}}
<input  type='submit'value="Registrar" />
</form>